### ISSUE TITLE
not running my rescript tests when I add other non-rescript tests

### ISSUE THREAD

**Issue by vasco3** [dusty-phillips/rescript-zora#5]
When I just run one test it works fine

I run the tests like this `"test": "pta 'tests/*.test.mjs'",`

```
tests/
- utils.test.res # generates utils.test.mjs and runs tests ok
```

but when I add normal test files to the mix, Zora only runs the non-rescript 

```
tests/
- utils.test.res # generates utils.test.mjs and but is not run by Zora
- api-utils.test.mjs # run by zora
- other-utils.test.mjs # run by zora
```

Any idea what might I been missing?

**Comment by dusty-phillips** [comment]
Good question. I don't _think_ it is related to whether the file is generated by Rescript. Rather, it seems like pta is neglecting to collect some tests. But I can't for the life of me guess why.

For example, when I run `npm test` in this repo, it is currently only running the two tests in `multiple_blocking.test.mjs`, but none of the others. Same happens if I manually invoke `npx pta tests/*.test.mjs`

But, like you say, it will run any one test file happily (ie. `npx pta tests/assertions.test.mjs`). The weirdest thing is if I run `npx pta tests/*.mjs` (instead of `tests/*.test.mjs`) it runs the tests in TWO file `multiple_blocking.test.mjs` and `simple.mjs`, instead of one, but none of the others. 

More complicated globs such as `npx pta tests/{assertions,catch}.test.mjs` collects the expected tests.

Puzzling.

**Comment by dusty-phillips** [comment]
Ah... workaround is to explicitly pass `--module-loader` to the pta command:

```
npx pta tests/*.test.mjs
```

So it seems `pta` doesn't know to check the file extension. I'm guessing if you put `"type": "module"` in your `package.json` it will work correctly, too.

**Comment by brettcannon** [comment]
Can this issue be closed?

**Comment by vasco3** [comment]
> Can this issue be closed?

yeah
